version: '3.8'

services:
  web:
    image: nginx:stable-alpine
    volumes:
      - ./:/var/www/html:cached
      - .docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app
    ports:
      - "9000:80"
    restart: unless-stopped
    networks:
      - news

  app:
    build:
      context: .
      args:
        user: php
        uid: 1000
      dockerfile: develop.Dockerfile
    volumes:
      - ./:/var/www/html:cached
      - ./tests/coverage:/opt/phpstorm-coverage
      - .docker/php/php_settings.ini:/usr/local/etc/php/conf.d/99-override.ini
      - .docker/php/xdebug.ini:/usr/local/etc/php/conf.d/20-xdebug.ini
    links:
      - db
    restart: unless-stopped
    networks:
      - news

  db:
    image: mysql:8.0
    command: --init-file /usr/local/etc/mysql/init.sql
    volumes:
      - mysql-data:/var/lib/mysql
      - .docker/mysql/conf.d:/etc/mysql/conf.d
      - .docker/mysql/init/init.sql:/usr/local/etc/mysql/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
    restart: unless-stopped
    ports:
      - "9003:3306"
    networks:
      - news

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: lucas-sandery
    links:
      - db
    ports:
      - "9001:8080"
    restart: unless-stopped
    networks:
      - news

  mail:
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "9002:1080"
    restart: unless-stopped
    networks:
      - news

networks:
  news:
    driver: bridge

volumes:
  mysql-data:
